In [1]:
print("Hello Mutual Fund Project")

Hello Mutual Fund Project

In [2]:
import pandas as pd

print(pd.__version__)

3.0.3

In [3]:
import pandas as pd

data = {
    "Fund": ["SBI Bluechip", "ICICI Bluechip"],
    "NAV": [105.4, 98.2]
}

df = pd.DataFrame(data)

df

             Fund    NAV
0    SBI Bluechip  105.4
1  ICICI Bluechip   98.2

In [4]:
import pandas as pd

fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [5]:
fund_master.shape

(40, 15)

In [6]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [7]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [8]:
fund_master.duplicated().sum()

np.int64(0)

In [9]:
fund_master["fund_house"].unique()

<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [10]:
fund_master["category"].unique()

<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [11]:
fund_master["sub_category"].unique()

<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

# Fund Master Data Quality Summary
- Total Rows: 40
- Missing Values: 0
- Duplicate Rows: 0
- Dataset Loaded Successfully

# Fund Master Data Quality Summary

## Dataset Information
- Rows: 40
- Columns: 15

## Data Quality Checks
- Missing Values: 0
- Duplicate Rows: 0

## Key Columns
- AMFI Code
- Fund House
- Scheme Name
- Category
- Risk Category
- Expense Ratio

## Status
Dataset passed all basic quality checks.

In [12]:
print("Fund Houses:")
print(fund_master["fund_house"].unique())

Fund Houses:
<StringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [13]:
print("Categories:")
print(fund_master["category"].unique())

Categories:
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [14]:
print("Sub Categories:")
print(fund_master["sub_category"].unique())

Sub Categories:
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [15]:
print("Risk Categories:")
print(fund_master["risk_category"].unique())

Risk Categories:
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [16]:
fund_houses = fund_master["fund_house"].nunique()

categories = fund_master["category"].nunique()

sub_categories = fund_master["sub_category"].nunique()

risk_categories = fund_master["risk_category"].nunique()

print("Unique Fund Houses:", fund_houses)
print("Unique Categories:", categories)
print("Unique Sub Categories:", sub_categories)
print("Unique Risk Categories:", risk_categories)

Unique Fund Houses: 10
Unique Categories: 2
Unique Sub Categories: 12
Unique Risk Categories: 5

In [17]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [18]:
nav_history.shape

(46000, 3)

In [19]:
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [20]:
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [21]:
nav_history.duplicated().sum()

np.int64(0)

In [22]:
nav_history["amfi_code"].nunique()

40

In [23]:
nav_history["date"] = pd.to_datetime(nav_history["date"])

print("Start Date:", nav_history["date"].min())
print("End Date:", nav_history["date"].max())

Start Date: 2022-01-03 00:00:00
End Date: 2026-05-29 00:00:00

In [24]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

nav_history.shape
nav_history.dtypes
nav_history.isnull().sum()
nav_history.duplicated().sum()

np.int64(0)

In [25]:
fund_codes = set(fund_master["amfi_code"])

nav_codes = set(nav_history["amfi_code"])

missing_codes = fund_codes - nav_codes

print("Missing Codes:", missing_codes)

print("Number of Missing Codes:", len(missing_codes))

Missing Codes: set()
Number of Missing Codes: 0

# NAV History Data Quality Summary

## Dataset Information
- Rows: 46,000
- Columns: 3

## Data Quality Checks
- Missing Values: 0
- Duplicate Rows: 0
- Unique AMFI Codes: 40

## Date Coverage
- Start Date: 2022-01-03
- End Date: 2026-05-29

## Status
Dataset passed all quality checks.