In [62]:
import pandas as pd

In [63]:
nav_history = pd.read_csv(
    "../data/raw/02_nav_history.csv"
)

nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [64]:
nav_history.shape

(46000, 3)

In [65]:
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [66]:
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [67]:
nav_history.duplicated().sum()

np.int64(0)

In [68]:
nav_history["date"] = pd.to_datetime(
    nav_history["date"]
)

nav_history.dtypes

amfi_code             int64
date         datetime64[us]
nav                 float64
dtype: object

In [69]:
nav_history = nav_history.sort_values(
    by=["amfi_code", "date"]
)

nav_history.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [70]:
(nav_history["nav"] <= 0).sum()

np.int64(0)

In [71]:
nav_history.to_csv(
    "../data/processed/nav_history_clean.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [72]:
investor_transactions = pd.read_csv(
    "../data/raw/08_investor_transactions.csv"
)

investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [73]:
investor_transactions.shape

(32778, 13)

In [74]:
investor_transactions.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [75]:
investor_transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [76]:
investor_transactions.duplicated().sum()

np.int64(0)

In [77]:
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [78]:
(investor_transactions["amount_inr"] <= 0).sum()

np.int64(0)

In [79]:
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [80]:
investor_transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [81]:
investor_transactions["transaction_date"] = pd.to_datetime(
    investor_transactions["transaction_date"]
)

In [82]:
investor_transactions.to_csv(
    "../data/processed/investor_transactions_clean.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [83]:
scheme_performance = pd.read_csv(
    "../data/raw/07_scheme_performance.csv"
)

scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [84]:
scheme_performance.shape

(40, 19)

In [85]:
scheme_performance.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [86]:
scheme_performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [87]:
scheme_performance.duplicated().sum()

np.int64(0)

In [88]:
scheme_performance.columns.tolist()

['amfi_code',
 'scheme_name',
 'fund_house',
 'category',
 'plan',
 'return_1yr_pct',
 'return_3yr_pct',
 'return_5yr_pct',
 'benchmark_3yr_pct',
 'alpha',
 'beta',
 'sharpe_ratio',
 'sortino_ratio',
 'std_dev_ann_pct',
 'max_drawdown_pct',
 'aum_crore',
 'expense_ratio_pct',
 'morningstar_rating',
 'risk_grade']

In [89]:
scheme_performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [90]:
scheme_performance.duplicated().sum()

np.int64(0)

In [91]:
scheme_performance[
    [
        "return_1yr_pct",
        "return_3yr_pct",
        "return_5yr_pct",
        "benchmark_3yr_pct"
    ]
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct  benchmark_3yr_pct
count       40.000000       40.000000       40.000000          40.000000
mean        14.376000       14.089000       14.516750          12.835500
std          4.883023        4.617253        4.454021           4.740972
min          4.260000        5.140000        5.430000           3.960000
25%         11.735000       12.035000       12.340000          10.690000
50%         14.620000       14.205000       14.185000          13.090000
75%         16.392500       15.882500       17.585000          14.775000
max         24.930000       23.390000       23.800000          22.160000

In [92]:
scheme_performance["expense_ratio_pct"].describe()

count    40.000000
mean      1.237000
std       0.386584
min       0.550000
25%       0.787500
50%       1.425000
75%       1.540000
max       1.640000
Name: expense_ratio_pct, dtype: float64

In [93]:
scheme_performance[
    (scheme_performance["expense_ratio_pct"] < 0.1) |
    (scheme_performance["expense_ratio_pct"] > 2.5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [94]:
scheme_performance["beta"].describe()

count    40.000000
mean      0.873250
std       0.224846
min       0.220000
25%       0.890000
50%       0.960000
75%       1.000000
max       1.040000
Name: beta, dtype: float64

In [95]:
scheme_performance["morningstar_rating"].unique()

array([4, 3, 5])

In [96]:
scheme_performance["risk_grade"].unique()

<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [97]:
scheme_performance.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully

In [98]:
scheme_performance.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

print("scheme_performance_clean.csv saved successfully")

scheme_performance_clean.csv saved successfully

In [99]:
category_inflows = pd.read_csv(
    "../data/raw/05_category_inflows.csv"
)

category_inflows.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [100]:
category_inflows.shape

(144, 3)

In [101]:
category_inflows.dtypes

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [102]:
category_inflows.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [103]:
category_inflows.duplicated().sum()

np.int64(0)

In [104]:
category_inflows.columns.tolist()

['month', 'category', 'net_inflow_crore']

In [105]:
category_inflows["category"].unique()

<StringArray>
[        'Large Cap',           'Mid Cap',         'Small Cap',
         'Flexi Cap',   'Large & Mid Cap',              'ELSS',
      'Value/Contra', 'Sectoral/Thematic',            'Liquid',
    'Short Duration',              'Gilt',            'Hybrid']
Length: 12, dtype: str

In [106]:
category_inflows["net_inflow_crore"].describe()

count      144.000000
mean      6473.881944
std       9718.335947
min        437.000000
25%       1801.250000
50%       4148.000000
75%       5304.000000
max      41952.000000
Name: net_inflow_crore, dtype: float64

In [107]:
category_inflows.to_csv(
    "../data/processed/category_inflows_clean.csv",
    index=False
)

print("category_inflows_clean.csv saved successfully")

category_inflows_clean.csv saved successfully

In [108]:
monthly_sip = pd.read_csv(
    "../data/raw/04_monthly_sip_inflows.csv"
)

monthly_sip.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [109]:
monthly_sip.shape

(48, 6)

In [110]:
monthly_sip.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [111]:
monthly_sip.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [112]:
monthly_sip.duplicated().sum()

np.int64(0)

In [113]:
monthly_sip.columns.tolist()

['month',
 'sip_inflow_crore',
 'active_sip_accounts_crore',
 'new_sip_accounts_lakh',
 'sip_aum_lakh_crore',
 'yoy_growth_pct']

In [114]:
monthly_sip[monthly_sip["yoy_growth_pct"].isnull()]

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN
5,2022-06,12276,5.60,7.50,5.18,NaN
6,2022-07,12140,5.65,9.21,5.25,NaN
7,2022-08,12694,5.71,8.90,5.31,NaN
8,2022-09,12976,5.80,9.40,5.41,NaN
9,2022-10,13040,5.93,9.52,5.55,NaN
10,2022-11,13306,6.00,8.80,5.62,NaN
11,2022-12,13573,6.05,7.60,5.70,NaN

In [117]:
monthly_sip["yoy_growth_pct"] = monthly_sip["yoy_growth_pct"].fillna(0)

In [118]:
monthly_sip.isnull().sum()

month                        0
sip_inflow_crore             0
active_sip_accounts_crore    0
new_sip_accounts_lakh        0
sip_aum_lakh_crore           0
yoy_growth_pct               0
dtype: int64

In [119]:
monthly_sip.to_csv(
    "../data/processed/monthly_sip_inflows_clean.csv",
    index=False
)

print("monthly_sip_inflows_clean.csv saved successfully")

monthly_sip_inflows_clean.csv saved successfully

In [120]:
aum_house = pd.read_csv(
    "../data/raw/03_aum_by_fund_house.csv"
)

aum_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [121]:
aum_house.shape

(90, 5)

In [122]:
aum_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [123]:
aum_house.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [124]:
aum_house.duplicated().sum()

np.int64(0)

In [125]:
aum_house.columns.tolist()

['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

In [126]:
aum_house.describe()

       aum_lakh_crore     aum_crore  num_schemes
count       90.000000  9.000000e+01    90.000000
mean         4.352889  4.352889e+05   152.200000
std          2.734328  2.734328e+05    52.108832
min          1.050000  1.050000e+05    56.000000
25%          2.525000  2.525000e+05    95.000000
50%          3.450000  3.450000e+05   172.500000
75%          5.675000  5.675000e+05   195.000000
max         12.500000  1.250000e+06   216.000000

In [127]:
aum_house.to_csv(
    "../data/processed/aum_by_fund_house_clean.csv",
    index=False
)

print("aum_by_fund_house_clean.csv saved successfully")

aum_by_fund_house_clean.csv saved successfully

In [128]:
industry_folio = pd.read_csv(
    "../data/raw/06_industry_folio_count.csv"
)

industry_folio.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [129]:
industry_folio.shape

(21, 6)

In [130]:
industry_folio.dtypes

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [131]:
industry_folio.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [132]:
industry_folio.duplicated().sum()

np.int64(0)

In [133]:
industry_folio.columns.tolist()

['month',
 'total_folios_crore',
 'equity_folios_crore',
 'debt_folios_crore',
 'hybrid_folios_crore',
 'others_folios_crore']

In [134]:
industry_folio.describe()

,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
count,21.000000,21.000000,21.000000,21.000000,21.000000
mean,19.829524,13.880476,2.776190,1.190000,1.983333
std,4.583376,3.207799,0.640308,0.274864,0.459079
min,13.260000,9.280000,1.860000,0.800000,1.330000
25%,15.540000,10.880000,2.180000,0.930000,1.550000
50%,19.980000,13.990000,2.800000,1.200000,2.000000
75%,23.890000,16.720000,3.340000,1.430000,2.390000
max,26.120000,18.280000,3.660000,1.570000,2.610000

In [135]:
industry_folio.to_csv(
    "../data/processed/industry_folio_count_clean.csv",
    index=False
)

print("industry_folio_count_clean.csv saved successfully")

industry_folio_count_clean.csv saved successfully

In [136]:
portfolio_holdings = pd.read_csv(
    "../data/raw/09_portfolio_holdings.csv"
)

portfolio_holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [137]:
portfolio_holdings.shape

(322, 8)

In [138]:
portfolio_holdings.dtypes

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [139]:
portfolio_holdings.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [140]:
portfolio_holdings.duplicated().sum()

np.int64(0)

In [141]:
portfolio_holdings.columns.tolist()

['amfi_code',
 'stock_symbol',
 'stock_name',
 'sector',
 'weight_pct',
 'market_value_cr',
 'current_price_inr',
 'portfolio_date']

In [142]:
portfolio_holdings.to_csv(
    "../data/processed/portfolio_holdings_clean.csv",
    index=False
)

In [143]:
benchmark = pd.read_csv(
    "../data/raw/10_benchmark_indices.csv"
)

benchmark.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [144]:
benchmark.shape
benchmark.dtypes
benchmark.isnull().sum()
benchmark.duplicated().sum()
benchmark.columns.tolist()

['date', 'index_name', 'close_value']

In [145]:
benchmark.to_csv(
    "../data/processed/benchmark_indices_clean.csv",
    index=False
)

In [146]:
import sqlite3

conn = sqlite3.connect(
    "../data/db/bluestock_mf.db"
)

print("Database Connected Successfully")

Database Connected Successfully

In [147]:
import os

print(os.listdir("../data/processed"))

['aum_by_fund_house_clean.csv', 'benchmark_indices_clean.csv', 'category_inflows_clean.csv', 'industry_folio_count_clean.csv', 'investor_transactions_clean.csv', 'monthly_sip_inflows_clean.csv', 'nav_history_clean.csv', 'portfolio_holdings_clean.csv', 'scheme_performance_clean.csv']

In [148]:
import pandas as pd
import sqlite3
import os

conn = sqlite3.connect("../data/db/bluestock_mf.db")

files = os.listdir("../data/processed")

for file in files:
    
    if file.endswith(".csv"):
        
        df = pd.read_csv(
            f"../data/processed/{file}"
        )
        
        table_name = (
            file
            .replace("_clean.csv", "")
        )
        
        df.to_sql(
            table_name,
            conn,
            if_exists="replace",
            index=False
        )
        
        print(
            f"{table_name} loaded successfully"
        )

print("\nAll tables loaded!")

aum_by_fund_house loaded successfully
benchmark_indices loaded successfully
category_inflows loaded successfully
industry_folio_count loaded successfully
investor_transactions loaded successfully
monthly_sip_inflows loaded successfully
nav_history loaded successfully
portfolio_holdings loaded successfully
scheme_performance loaded successfully

All tables loaded!

In [149]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

                    name
0      aum_by_fund_house
1      benchmark_indices
2       category_inflows
3   industry_folio_count
4  investor_transactions
5    monthly_sip_inflows
6            nav_history
7     portfolio_holdings
8     scheme_performance

In [150]:
for table in [
    "aum_by_fund_house",
    "benchmark_indices",
    "category_inflows",
    "industry_folio_count",
    "investor_transactions",
    "monthly_sip_inflows",
    "nav_history",
    "portfolio_holdings",
    "scheme_performance"
]:
    
    query = f"""
    SELECT COUNT(*) as rows
    FROM {table}
    """
    
    print(table)
    print(pd.read_sql(query, conn))
    print("-"*50)

aum_by_fund_house
   rows
0    90
--------------------------------------------------
benchmark_indices
   rows
0  8050
--------------------------------------------------
category_inflows
   rows
0   144
--------------------------------------------------
industry_folio_count
   rows
0    21
--------------------------------------------------
investor_transactions
    rows
0  32778
--------------------------------------------------
monthly_sip_inflows
   rows
0    48
--------------------------------------------------
nav_history
    rows
0  46000
--------------------------------------------------
portfolio_holdings
   rows
0   322
--------------------------------------------------
scheme_performance
   rows
0    40
--------------------------------------------------

In [151]:
query = """
SELECT
    scheme_name,
    aum_crore
FROM scheme_performance
ORDER BY aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                         scheme_name  aum_crore
0  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
1      Kotak Emerging Equity Fund - Regular - Growth      47469
2     Nippon India Small Cap Fund - Regular - Growth      43630
3         DSP Top 100 Equity Fund - Regular - Growth      41828
4                UTI Mid Cap Fund - Regular - Growth      41728

In [152]:
query = """
SELECT
    AVG(nav) AS avg_nav
FROM nav_history;
"""

pd.read_sql(query, conn)

      avg_nav
0  269.570265

In [153]:
query = """
SELECT
    risk_grade,
    COUNT(*) AS fund_count
FROM scheme_performance
GROUP BY risk_grade;
"""

pd.read_sql(query, conn)

        risk_grade  fund_count
0             High           8
1              Low           6
2         Moderate          16
3  Moderately High           4
4        Very High           6

In [154]:
query = """
SELECT
    category,
    ROUND(AVG(expense_ratio_pct), 2) AS avg_expense_ratio
FROM scheme_performance
GROUP BY category
ORDER BY avg_expense_ratio DESC;
"""

pd.read_sql(query, conn)

           category  avg_expense_ratio
0              ELSS               1.60
1             Index               1.57
2         Flexi Cap               1.54
3   Large & Mid Cap               1.52
4             Value               1.41
5           Mid Cap               1.37
6         Small Cap               1.35
7         Large Cap               1.26
8         Index/ETF               0.89
9            Liquid               0.71
10             Gilt               0.66
11   Short Duration               0.56

In [155]:
query = """
SELECT
    category,
    SUM(net_inflow_crore) AS total_inflow
FROM category_inflows
GROUP BY category
ORDER BY total_inflow DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

            category  total_inflow
0             Liquid      451275.0
1  Sectoral/Thematic      103829.0
2          Flexi Cap       63989.0
3    Large & Mid Cap       57752.0
4     Short Duration       55530.0

In [156]:
query = """
SELECT
    SUM(sip_inflow_crore) AS total_sip_inflow
FROM monthly_sip_inflows;
"""

pd.read_sql(query, conn)

   total_sip_inflow
0            939721

In [157]:
query = """
SELECT
    AVG(sharpe_ratio) AS avg_sharpe
FROM scheme_performance;
"""

pd.read_sql(query, conn)

   avg_sharpe
0     1.36175

In [158]:
query = """
SELECT
    scheme_name,
    sharpe_ratio
FROM scheme_performance
ORDER BY sharpe_ratio DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                    scheme_name  sharpe_ratio
0      ICICI Pru Liquid Fund - Regular - Growth          7.68
1          Kotak Liquid Fund - Regular - Growth          6.18
2           ABSL Liquid Fund - Regular - Growth          5.14
3  HDFC Short Term Debt Fund - Regular - Growth          1.84
4  SBI Magnum Gilt Fund - Regular Plan - Growth          1.52

In [159]:
query = """
SELECT
    fund_house,
    ROUND(AVG(aum_crore), 2) AS avg_aum
FROM scheme_performance
GROUP BY fund_house
ORDER BY avg_aum DESC;
"""

pd.read_sql(query, conn)

                 fund_house   avg_aum
0           DSP Mutual Fund  38262.33
1         Kotak Mahindra MF  36422.25
2  Aditya Birla Sun Life MF  34702.67
3           Nippon India MF  30865.60
4       ICICI Prudential MF  24048.20
5          Axis Mutual Fund  23052.50
6           UTI Mutual Fund  22330.00
7            Mirae Asset MF  21132.00
8           SBI Mutual Fund  18988.00
9          HDFC Mutual Fund  17395.00

In [160]:
query = """
SELECT
    transaction_type,
    COUNT(*) AS total_transactions
FROM investor_transactions
GROUP BY transaction_type;
"""

pd.read_sql(query, conn)

  transaction_type  total_transactions
0          Lumpsum                8095
1       Redemption                4967
2              SIP               19716